### ISSUE TITLE
Bookmarklet::does not connect collections

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#1075]
The bookmarklet collection function is not working.
![screen shot 2016-04-07 at 5 32 00 am](https://cloud.githubusercontent.com/assets/8831502/14346853/271eb1d4-fc82-11e5-8272-c4f5c722aff2.png)

**Comment by horak** [comment]
@rchen152, do you think you could look into this?

**Comment by rchen152** [comment]
Hmm, I'll look into this more carefully tomorrow afternoon when I have time, but that drop-down is populated by web/js/app/zeega.widget.js, which is loaded by web/js/loaders/widget.js in app/Resources/views/widget.base.html.twig.

The problem seems to be that some of the scripts that widget.js tries to load either don't exist or have been moved, so the whole thing fails with a timeout error.
