### ISSUE TITLE
Searching with a hash generates query error

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#298]

**Comment by lfbrandao** [comment]
Weird; this was working a couple of days ago. For some reason I'm not
getting the query text on the backend every time a # is included. My first
guess is that the URL needs to be encoded to escape the # before making the
call to the API, but since it was working before I'll check what changed on
my side first.

On Wed, Jun 27, 2012 at 12:14 AM, Jesse Shapins <
reply@reply.github.com
