### ISSUE TITLE
IE :: Home page search doesn't load

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#341]

**Comment by kanarinka** [comment]
This seems to be my day of long, slow bug fixes wherein I don't fix them! The search on the home page isn't loading in IE (what I have found is it actually loads sometimes and not other times depending on whether the JS files are cached or not - is that what you were experiencing Jesse?) because IE9 is somehow not loading the files in the right order. In particular it seems to trip up on loading the Underscore library which the visualsearch.js requires. I've spent awhile on this bug browsing forums for require.js and order.js and digging around into how we load things and am happy to spend longer but it might make more sense for James (or someone who has worked on our loading structure) to do this more efficiently. The order.js plugin should be taking care of this and I don't really understand why it's not working for IE9.
