### ISSUE TITLE
IE :: points on map don't open pop-up

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#344]

**Comment by kanarinka** [comment]
This is happening because OpenLayers.js is doing an XMLHttpRequest and IE9 is blocking this because of the cross-domain policy - it gives the error SCRIPT5: Access is Denied. 

Is there some kind of setting we can do on the server like --- header('Access-Control-Allow-Origin: *'); --- that would just allow these through? Or somewhere on the client side where we could configure this?
