### ISSUE TITLE
FF Mac :: audio doesn't load in collections player

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#347]

**Comment by kanarinka** [comment]
hey guys - i just changed the browser detection to allow firefox & IE but the collections player doesn't play my collection in FF - just hangs while loading. Jesse - how were you playing a collection in FF on Mac previously? I can try debugging this bug but wanted to make sure that I'm not missing something.

**Comment by jshapins** [comment]
I wouldn't worry about this xBrowser bug until the end, as it's basically
making the Zeega Player xBrowser compatible.

On Tue, Jul 3, 2012 at 11:51 AM, kanarinka <
reply@reply.github.com

**Comment by kanarinka** [comment]
Sorry - I think I wasn't clear - I made it so that FF doesn't get redirected to the "Bad Browser" page now. What it does now is just hang on loading. So I wasn't sure how you had logged a bug that audio doesn't work in the collections player for FF because nothing works in the collections player for FF. Let me know if you want me to do something further on this (or redirect FF to the Bad Browser page?) ?
