### ISSUE TITLE
For "news article" items, text and photograph show up only in the javascript popup, and not on the item page

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#586]
(https://f.cloud.github.com/assets/2146722/655315/1a810a9a-d510-11e2-90ff-6aa3c44d278b.png)

**Comment by hsenju** [comment]
I'm having trouble finding the "item page" of a news article. Could you perhaps link it to me? Thanks!

**Comment by corinnecurcie** [comment]
In the pop-up for a news article, there's a "link" button above the
picture, which will give you a URL. Here's one:
http://jdarchive.org/en/item/1515926

On Tue, Aug 27, 2013 at 5:04 PM, hsenju notifications@github.com wrote:

> I'm having trouble finding the "item page" of a news article. Could you
> perhaps link it to me? Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/586#issuecomment-23370639
> .

## 

Corinne Curcie
Harvard University
Class of 2015
Computer Science

**Comment by hsenju** [comment]
thanks!

**Comment by hsenju** [comment]
The issue regarding the item picture and description not showing up is that 1)the link to the picture on the item page is not the link to the picture but instead the link to the original webpage and 2) the item description doesn't appear because it's not being rendered in the html (checking $('#item') in the browser console reveals that the
item.description is successfully being gotten).  I got the rendering of the text to work but there still needs to be work done on getting the correct news article image link.
