### ISSUE TITLE
Urgent :: Tags, translations, and translation edits no longer sticking in db

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#591]
Adding new tags or new translations, or edits to existing translations do not stick in the database. I've tested this on several items and confirmed the issue.

Obviously these things were all working fine until recently. Have we changed anything?

**Comment by jessyurko** [comment]
I think it was probably something I did, sorry about that. Should be fine now. Let me know if it happens again and I'll take another look.

**Comment by nickkapur** [comment]
@jessyurko Thanks for the input. Hmm, as of right now they are definitely not working again. I'll reopen this issue for now and test again later on...

**Comment by nickkapur** [comment]
So this is definitely not something Jessica did - she has not pushed anything to the live site.

**Comment by ebensing** [comment]
So, it looks like SOLR can just randomly screw up and needs to be restarted. Fortunately, we will never _lose_ data because of this, but it wont be showing up on the front end. fortunately, the fix is pretty easy. Just SSH into production and `sudo service tomcat7 restart` I'll create a wiki entry for this.
