### ISSUE TITLE
Add loose pdfs to db

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#603]
Find out how best to add loose pdfs to the db. Document Cloud? AWS?

**Comment by ebensing** [comment]
look into the document cloud stuff

**Comment by ebensing** [comment]
Looks like we'll need to use DocumentCloud if we want to have them in the archive as "documents"

If we have an account, I'll need to login info. If not, creating a new one isn't a problem. I'll then create a bulk upload script so that we can upload the current PDFs and new ones as they come in.

@nickkapur any idea on old credentials?

**Comment by kyleparry** [comment]
Just making sure you guys know we already have a few PDFs in archive as
docs. The login we used way back was mine:

http://www.documentcloud.org/login

<redacted>

**Comment by ebensing** [comment]
awesome Kyle, thanks for the info. I've moved it from github because it seems a little bit like a bad idea to have it posted publicly, but I'll get it somewhere in the archive.

**Comment by kyleparry** [comment]
woops - consider that a dull morning error!

**Comment by ebensing** [comment]
done!
