### ISSUE TITLE
Team Page :: Japanese localization

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#720]
Already localized in google doc.

**Comment by corinnecurcie** [comment]
Reminder to me: send the google doc

**Comment by corinnecurcie** [comment]
English is in translation->messages.en.xliff
Japanese '' .ja.xliff"

xliffs:

{% trans %} {{team.webdeveloper.title}} {% endtrans?? %}  Corinne Curcie

**Comment by corinnecurcie** [comment]
I don't actually think there's a google doc, as far as I can tell... Ryo would you be able to provide translation? I think just doing the titles would be fine if you don't want to go through the hassle of giving everyone katakana for their names. But this is very low priority.

**Comment by meeshmon** [comment]
I will work on this. It would be a good airplane project tomorrow.

**Comment by nickkapur** [comment]
There is a google doc, will share with you both.

**Comment by corinnecurcie** [comment]
Hey Zahra, here's the google doc with the english and japanese team names. Basically, everything in red is what's currently on the team page, and everything in black is what needs to be added for the japanese version. https://docs.google.com/document/d/1eVOVUz2aMVhvBo242xLzzCQ648neEWyPTKx4HTqMqeM/edit

As you saw when you added your name to the team.html.twig page, all the text is directly in the document. However, on most of our other pages, the text is in translation documents: src/JDA/CoreBundle/Resources/translations/messages.en.xliff and messages.ja.xliff, corresponding to English text and Japanese text respectively. If you look at either translation xliff document, the entries in the document are each given titles that correspond to text. So for this page, you want to make entries like team.webdeveloper.corinne which will correspond to "Project Technical Lead: Corinne Curcie" in messages.en.xliff but will be "プロジェクト技術部リーダー：Corinne Curcie　（コリン・カーシー）" in messages.ja.xliff. Then, instead of the entry in team.html.twig being `<p>Project Technical Lead: Corinne Curcie<br/>`, it will be `<p>{% trans %} {{team.webdeveloper.corinne}} {% endtrans?? %}<br/>`. 

So by the end, the messages.en.xliff and messages.ja.xliff files will have a bunch of new entries corresponding to the lines in the google doc, and our team.html.twig page will not have any straight text on it. It can be very tedious to add all the new entries to the xliff documents, but this is a very easy task otherwise!

**Comment by corinnecurcie** [comment]
And actually, you can see in team.html.twig that most of the headings already have translations, like `{% trans %}jda.about.team{% endtrans %}`, so don't worry about those. However, if you actually go to the team page and click "日本語" to see the japanese translation, one of them doesn't translate, probably because it doesn't have an entry in messages.ja.xliff, so make sure you add that one.

**Comment by corinnecurcie** [comment]
Thank you Zahra this looks great!
