### ISSUE TITLE
Item table :: what is "location" field for?

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#727]

**Comment by nickkapur** [comment]
Pretty sure this is doing nothing. Let's make sure and then get rid of it.

**Comment by corinnecurcie** [comment]
Getting rid of a row in a table is more trouble than it's worth. This requires updating the schema of SOLR and making sure it jives with our MySQL. If the location field were required for importing data, I'd agree on changing that, but since it's not required I don't think this issue is worth doing. There is very little benefit, but the work involved and the potential for screwup are not insignificant.
