### ISSUE TITLE
Testimonials :: Testimonial item page has a link that says "View on JDA Testimonials" or sometimes "View Testimonial" that leads to a random item in the archive or sometimes nowhere

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#750]
Not sure what is going on here, but presumably these links should simply be eliminated.

**Comment by HakuG** [comment]
I'll work on this one.

**Comment by HakuG** [comment]
So it doesn't seem like I can even access these files? If I try to go to source-link on my dev website, I don't find the file, as in it doesn't exist for me. I'll get back to this one once I understand more from corinne.

**Comment by HakuG** [comment]
I've been trying to figure this one out for too long... Here's what I've obtained: 

It's under multiple different queries, especially, outerHTML, outerText, pathname, innerHTML, innerText, and href. It's all combined to a thing in a file called jquery-1.7.1.min.js, which is a very disgusting looking file, with three lines of code for what seems to be tons of tons of tons of code. There's something in there, or some other file, require-jquery.js, that has that file that's rather questionable and assigns values to HTML. I'll probably check it out in the morning, but that's my progress so far. Once I figure out how to access these values, I can probably knock out a few other bugs, since a lot of them are linked to this, but I have literally no idea how to access these DOM elements.

**Comment by HakuG** [comment]
Just fixed it, I think, but not sure.
