### ISSUE TITLE
Bookmarklet ::: Unable to add items

### ISSUE THREAD

**Issue by annawada** [Japan-Digital-Archives/Japan-Digital-Archive#754]
The "Add Media" button doesn't seem to be functioning on my Chrome or Firefox browsers.

**Comment by HakuG** [comment]
I'm going to try to take this one while I wait for confirmation on the others.

**Comment by HakuG** [comment]
I can't log-in to my own jdarchive, and since I'm still sorta new, I'd rather have someone else work with the actual database to add new things, but the problem seems to be here: In src\JDA\CoreBundle\REsources\views\Widget\widget.html.twig, 

<h3>Tags (comma separated):</h3>

```
        <div id="tags">
            <td>
      <select name="tagsSelect" id="tagsSelect" multiple>
      </select>
    </td>
        </div>
```

You need to add a way to give tags. Currently, it's not even a textbox, so when you call "split" on it, you get a null value, which returns badly. All you need to do is change the above code to this:

<h3>Tags (comma separated):</h3>

```
        <div id="tags">
            <td>
```

<div class="widget-textbox ingest-info">
              <textarea id="widget-tags" ></textarea>
        </td>
            </div>

I have no idea if the <td> is even necessary, or what the <select> was trying to do, but this fits the "split" function protocols... However, I am, sadly, too afraid to do any of this in the real database (someone look this over TT-TT), so if @corinnecurcie or any other technical head could help me out, that'd be wonderful. 

Edit: I have no idea how to change this formatting that github is doing to my recommended code. I'm literally a flailing penguin right now.

**Comment by jessyurko** [comment]
I can look into this this afternoon.

**Comment by jessyurko** [comment]
https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/commit/21852be1e8fd8c8d47ced31b74418aaec34a8eed#diff-d42a2cba7df482d8b025c35ee4950e98

I don't know the background on this change, but seems like the removal of the textarea in the commit above is where the error is coming from.

**Comment by HakuG** [comment]
Yeah. That's what I was thinking too. I dont' have access to the real database, so I can't change anything though. The textarea shouldn't be removed...

**Comment by karashen** [comment]
Corinne and I were working on the bug that existed with Japanese commas and were messing around with the tags part - we still haven't been able to figure this out, which is why the code is faulty.

**Comment by nickkapur** [comment]
@karashen @corinnecurcie Well at the very least we should roll back the changes in the meantime so that the bookmarklet works the way it used to!

**Comment by nickkapur** [comment]
I believe we have rolled back these changes.
