### ISSUE TITLE
New AJW Import :: No images and text shows html markup

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#786]

**Comment by corinnecurcie** [comment]
Email explaining photo issue from Prof. Gordon (definitely needs more research - he may believe this is the case, but it could be a fault on our end as well):
"Regarding the AJW articles, you’ll see if you look at the more recent ones (from 2013), that photos do not show up, whereas in the earlier ones, we do get the photos.   The reason for this is apparently that, at a certain point along the way, Asahi decided that it was going to block all users from the ability to download the photos, which is making impossible for them to show up in our archive.  At least, that seems to be the reason.   I am not sure how important it is to have the photos accompany the articles, but is there anyway that, if AJW let us pull in those photos, we could make it impossible for a user to download them?  That might make it possible for us to get them to release the photos to us.  Please let me know; not urgent."

**Comment by theannielin** [comment]
When I go to the sources for the images of the AJW articles, it brings me to an XML file that tells me access denied (for example, https://s3.amazonaws.com/JDA-Files/AJ201303070093M.jpg).

**Comment by corinnecurcie** [comment]
Okay, so from what I can tell, AJW will sometimes FTP into our server and drop off a bunch of articles. We then FTP in as well, and run a script that scrapes the important data from the articles and then imports the data into our database, so that we can display links to the articles on our archive. See here: https://github.com/Japan-Digital-Archives/scripts/wiki/Asahi-Asia-&-Japan-Watch-Import-Notes

The script in question is here: https://github.com/Japan-Digital-Archives/scripts/blob/master/ajw.py 
As you can see, the photo link is created in this chunk of code:

```
# Get first photo and caption from second <block>
    if root.find(".//block/media") is not None:
        for photo in root.findall(".//block/media"):
            photo_type = photo.find(".//media-metadata").attrib.get("value")
            if photo_type == "photo-middle":
                photo_medium = photo.find(".//media-reference").text
                article_photo.append(photo_medium)
        if len(article_photo) > 0:
            article_photo = "https://s3.amazonaws.com/JDA-Files/" + article_photo[0]

```

Don't worry about all the //block/media stuff, that's just rooting through the XML to get the data. However, I don't see anything in this script that actually downloads the files from AJW or from our server, where AJW could have dropped the photos along with the articles, and so these photos are never getting uploaded to our S3 AWS account at all. All this script does is piece together a link which then has to work through other means. 

Previously, it looks like we WERE actually storing these photos ourselves, because I have access to the S3 AWS console, and when I go into the JDA-Files bucket, I see photos with the same format link, but the dates only up to https://s3.amazonaws.com/JDA-Files/AJ201212310080M.jpg, which is obviously from 2012-12-31, while the photo in Annie's example link is 2013-03-07. So previously we were clearly doing something with the photos that got them on our S3 bucket on AWS, but in the most recent update we didn't do that. 

@nickkapur - when AJW was dropping articles into our server through FTP, were they also dropping the photos there too? Was there any other script besides this one for downloading photos, either from our server or from AJW's end, and putting them in our S3 account? Unfortunately the instructions on our end say to delete everything in the FTP folder after running the script, so I can't see what has been uploaded there before. And if we want to actually get the photos for the articles affected by this issue, we'll have to ask AJW specifically to either upload them on our server again or give us links to them (depending on how that originally worked, which again I don't know), because it looks like we never did anything with them in the first place. 

@meeshmon This is also something you might know, re: the questions I asked Nick above. 

Unfortunately I've never actually done the AJW import myself and don't know what the content that they drop off looks like, whether it's just articles/XML files, or if there are image files as well. Until we are able to have access to AJW's photos again, the photo links that we have in our archive aren't going to work.

So @theannielin, we have to wait for more information regarding the photos for now. Otherwise, the HTML markup can be taken care of with a script. If you're not comfortable or knowledgable with running scripts on the database directly, one of the easiest ways to do this is by adding a flag to something like the ingestion command, found in /var/www/zeega/src/Zeega/IngestionBundle/Command/PersistCommand.php. You can add a flag (currently there are ones like --check_for_duplicates or otherwise) that pulls the items for AJW and edits the "text" field (where the article and markup is) to not include the markup. **At first, test this with a very small number of files of AJWs to test if your script works.** You'll also have to make sure that the files you pull to edit are the ones from the most recent update, which means they all have a "date_created" (NOT media_date_created) of April 30, 2014, so filter for that date as well. AJW is user 468 so you can use that and the date for the database query. If you have any questions please ask me. An example of the kind of markup that's in the files can be seen in the "text" field here: http://jdarchive.org/admin/zeega/data/item/1698321/edit.

**Comment by nickkapur** [comment]
Unfortunately, I never did it myself either. Molly was totally in charge of that, so you can check with her at mollydes@upenn.edu.  But all that said, I am 99% positive that the images were also in the FTP folder. I'm not sure how we handled them, but I guess we uploaded them to S3? Again, Molly should know, and if not her, then EJ.

**Comment by meeshmon** [comment]
@corinnecurcie Unfortunately I do not know it either. But I would like to ask if there is any way for us to find out where the batch AJW send us for the headlines between Septermber 2013 to April 2014 went. Do you think this is something we could recover? I have been trying to be in touch with AJW, but they are not being responsive...

**Comment by corinnecurcie** [comment]
Last night I exhausted all options for trying to recover the images and the headlines you mentioned Ryo, and I wasn't able to do it unfortunately. So we will have to wait for AJW.

**Comment by meeshmon** [comment]
Now they have finally resent the lost data. Please import them as soon as we can. @corinnecurcie @theannielin

**Comment by corinnecurcie** [comment]
Okay, the new data has been added (and photos have been uploaded)! We are still missing old photos from Jan-Aug 2013. I haven't updated the markup text yet either. But the new import looks good and there is no issue with the text from what I can tell.

**Comment by meeshmon** [comment]
@corinnecurcie Ok wonderful! Make sure to do backup in case something happens to the data before I will tell them to upload another batch. This time we cannot screw up! I will try to assess the timing for asking about the missing photos from Jan-Aug 2013.

**Comment by corinnecurcie** [comment]
Yes, I made a backup and everything looks good for this. Also the photo uploading was very simple and it doesn't need it's own separate script, which is good but something that definitely wasn't realized by Harnek and I when we did the previous upload that was all screwed up. 

Also, I think I just fixed the HTML issue, so we can close this I think!

**Comment by nickkapur** [comment]
Hooray! Glad this got figured out and was not as bad as we thought.
