### ISSUE TITLE
the Yahoo photos seem to have been disconnected from our archive - a possible API issue? 

### ISSUE THREAD

**Issue by meeshmon** [Japan-Digital-Archives/Japan-Digital-Archive#808]

**Comment by corinnecurcie** [comment]
Amazon RDS has "restore database to certain point in time feature". I'm slightly worried this will just restore to closest earlier backup, which would be the 2013 one, but maybe not. I'm looking for ways to be able to join our 2013 backup with our current one, but I haven't found a solution yet. 

If I restore to point in time, I would probably do July 1, since we discovered the Yahoo photos were gone on July 23. However, I may have to redo some of the Michinoku photo stuff if this is the case (but I will have to redo some anyway because of the Irides issue, so I am not too worried about that). 

I do not think we have made any other big leaps in content since July 1, so these seems like a viable alternative to me if we know it's not going to defer to the 2013 backup.
