### ISSUE TITLE
Admin Dashboard_ID1839723~1908466_resulted 500 Internal Server Error

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#822]
Newly imported items on 9/20/14 betweenID1839723~1908466 resulted in "500 internal Server Error" when I opened the edit page.
![error in admin yahoo jpg copy](https://cloud.githubusercontent.com/assets/8831502/4346220/12abfb82-40f2-11e4-8e20-e9d2a0bfdd47.jpg)

**Comment by corinnecurcie** [comment]
So I was able to separately restore an old backup of our database and pull
the Yahoo! and Hypercities items out of there with all their data intact.
So I have a huge JSON file of all the items that were lost, and I'm
currently trying to reimport it into the database. Unfortunately, it looks
like even though I included the "id" in the data for each item, hoping to
get them in the original places of items 1-173123, our import script
ignores that ID and just appends things at the "end" of the database, after
the last item currently in there. I believe I can fix this and get the
items in the proper places, it will just take longer and I will have to
change some of the zeega code for how data is ingested.

The 500 error may be because I haven't run the "dataimport" from SOLR yet,
but I'm not positive.

On Sat, Sep 20, 2014 at 4:46 PM, meeshmon notifications@github.com wrote:

> Assigned #822
> https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/822
> to @corinnecurcie https://github.com/corinnecurcie.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/822#event-168090886
> .

## 

Corinne Curcie
Harvard University
Class of 2015
Computer Science
