### ISSUE TITLE
Fukushima Disaster Archive:: multiple probelms in pop-ups and item pages.

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#826]
Fukushima Disaster Archive, user ID http://jdarchive.org/ja/user/515
<Pop-up pages>
1. Pop-up pages　→ images do not appear
2.　"Add to"→　I do not know what the "Add to" function does for the JDA site.
3.  "Link" functions do not open even when I click, so I cannot search id numbers.

<Item pages>
1. images and pdfs do not appear in item pages
2. Links to Fukushima Digital Archive say "View on Yahoo! Japan"

![fda item problems](https://cloud.githubusercontent.com/assets/8831502/4391646/18c5424a-4407-11e4-97b2-3c29ca2f0bff.png)

**Comment by corinnecurcie** [comment]
Thanks Koko.

This is interesting - I tested it out, and for me the "Add to" button
doesn't show up the first time I open an item in the popup. However, if I
close that item, and then open it up again, the "Add to" button does show
like your picture! And when it does show, you are correct, the Link button
does not work.  I believe the "Add To" button's is supposed to allow users
to add it to one of their collections directly from the popup, so that they
do not have to exit the popup and drag it over to the toolbar on the right
hand side. The reason it doesn't show up the first time is because we
disabled it for now since it's not functioning correctly, and it's clear
that this disabling does occur when the user first opens an item, but not
the second or after times. I did not realize this was happening, so thank
you for seeing this!

And yes, the images and the "Yahoo! Japan" are errors from the data import.
I will have to clean that up.

Thank you for the error reporting! I have assigned myself the error in
Github and hopefully I will be able to tackle it after the Yahoo items,
which I want to do this weekend.

On Wed, Sep 24, 2014 at 12:36 PM, jdaKoko notifications@github.com wrote:

> Fukushima Disaster Archive, user ID http://jdarchive.org/ja/user/515
> 1. Pop-up pages → images do not appear
> 2. "Add to"→ I do not know what the "Add to" function does for the JDA
>    site.
> 3. "Link" functions do not open even when I click, so I cannot search id
>    numbers.
> 4. images and pdfs do not appear in item pages
> 5. Links to Fukushima Digital Archive say "View on Yahoo! Japan"
> 
> [image: fda item problems]
> https://cloud.githubusercontent.com/assets/8831502/4391646/18c5424a-4407-11e4-97b2-3c29ca2f0bff.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/826
> .

## 

Corinne Curcie
Harvard University
Class of 2015
Computer Science

**Comment by jdaKoko** [comment]
Corinne,
Thank you very much for the message and for trying to fix many issues.  I will be uploading a lot of bugs (unfortunately) as I go along checking the website and the admin pages. You and Ryo can discuss the priority of work.  Now that the JDA search came back after you did the SOLR dataimport, and the collection pages are working, I am good to do my work.  **(@.@)/**

**Comment by jdaKoko** [comment]
Follow up on the pop-ups.  I opened up the same Fukushima Disaster Archive item in Safari, Firefox, and Chrome.  The appearance of the popups were not consistent from yesterday to today. Could it be that pop ups look different from day to day or based on time of submission or import?  I use three different browsers for my work, so the inconsistency sometimes inconveniences me a little. The issue is not interfering with my work, but I am just letting you know about the bugs I see.
![pop ups in 3 browsers](https://cloud.githubusercontent.com/assets/8831502/4414862/beca39b0-4520-11e4-805a-6c00f6dfb814.png)

**Comment by corinnecurcie** [comment]
Okay, I've isolated some of the issues:
The images not showing up is because in popups is because they are PDFs, and  we don't have them uploaded to DocumentCloud. So the console brings up an error message like "Failed to load resource: the server responded with a status of 404 (Not Found) http://www.documentcloud.org/documents/http://fukushima.archive-disasters.jp/infolib/id/M2013011818155472579?_=1414295539162"

The "View on Yahoo! Japan" is data issue. 

The "Add to" showing up also seems to trigger the mystery box where the map should be and the tagging issue, so hopefully those can all be resolved together.

**Comment by corinnecurcie** [comment]
@jdaKoko + @meeshmon : I changed the PDFs to display as a link like the Internet Archive PDFs do. Is that okay? There is no preview image larger than the thumbnail in Fukushima's API, so we unfortunately don't have a nice way of previewing the document. If you think something else would be better, let me know, but I think this is better than the blank space that was there before.

Still working on the "Add to"/tag stuff. 

![image](https://cloud.githubusercontent.com/assets/3768712/4782021/dbc677fc-5cd3-11e4-9e6a-a14de3215188.png)

**Comment by corinnecurcie** [comment]
Hi @jdaKoko and @meeshmon  - I believe this item should be fixed now. The mystery box, tagging, and "Add to" issues were actually appearing in all non-geolocated items, so thank you for finding this! Those issues stemmed from some the mapbox script generating 2 seperate maps - the map for the geolocated data (which in this case is a blank mystery box because the item isn't geolocated), and the "No location" map which just appears like a grayed out map showing Japan (the bottom one). 

The lack of image showing up was due to a data issue that should be fixed for most things now. 

Please confirm that this is fixed!

**Comment by meeshmon** [comment]
It looks like this problem is fixed. Great job Corinne!

**Comment by jdaKoko** [comment]
I will temporary unpublish 21 Fukushima Disaster Archive "Website" items, I will re-publish after the export on Nov. 1, 2014. This is the prevension act that all published "Website" items going into the export page.

![fukushima disaster archive](https://cloud.githubusercontent.com/assets/8831502/4802187/9b8f63ac-5e3f-11e4-85e5-7ccaceec1413.png)
