### ISSUE TITLE
Item page:: please link to Internet Archive

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#831]
Item page inconsistancy started to occur ID 1475610. 

1.)After ID 145610, item pages only linked to live links.  The item page "View on seeds" Fig 2. or "View  on Internet Archive" Fig 3 is supposed to link to IA wayback page Uri\* .  Linking to Internet Archive is very important. The National Diet Libray Disaster site, "Hinagiku" links to the JDA item page.
Fig 2.
![item pages after jan 24 14](https://cloud.githubusercontent.com/assets/8831502/4469350/361698ae-4910-11e4-9cef-7feca1761e10.png)
Fig 3.
![item page through_bookmarklet](https://cloud.githubusercontent.com/assets/8831502/4469352/46848e3a-4910-11e4-969b-e6129194ca36.png)

2.)
Item pages look different depending on whether the item has been submitted using conventional submission Fig 4c "View on seeds" or submission using bookmarklet Fig 4b "View on Internet Archive".

![item page-not linked to wayback page 9 30 14](https://cloud.githubusercontent.com/assets/8831502/4469397/dbf525ce-4910-11e4-9596-0b35f5fff2ee.png)

When fixing this issue, please leave website category item pages before 1475610 as they are now.

**Comment by corinnecurcie** [comment]
This is really stupid.... even though we have the wayback archived page, for some reason the container in both cases is relying on the attribution-uri, which is the NON-archived page. The attribution URI for the container that's broken, predictably leads to a broken link: http://medg.jp/mt/2012/05/vol493.html

The attribution URI for the container that's working is a working link: http://ameblo.jp/kaze-amb/entry-11906798808.html.

Instead of using the wayback archive to display the cached page, we're just displaying the attribution-uri which is the non-cached page, and so it's broken when the non-cached page breaks, which is obviously a problem since most pages for news that aren't just a cached page are eventually deleted. 

Item 1834822 container (WORKING):
<div id="item" class="jda-item-container" data-layer_type="Website" data-attribution_uri="http://ameblo.jp/kaze-amb/entry-11906798808.html" data-text="" data-media_type="Website" data-uri="http://wayback.archive-it.org/2438/20110301000000/http://ameblo.jp/kaze-amb/entry-11906798808.html">

Item 1475821 container (BROKEN):
<div id="item" class="jda-item-container" data-layer_type="Website" data-attribution_uri="http://medg.jp/mt/2012/05/vol493.html" data-text="" data-media_type="Website" data-uri="http://wayback.archive-it.org/2438/20110301000000/http://medg.jp/mt/2012/05/vol493.html">

**Comment by jdaKoko** [comment]
Thank you again!
