### ISSUE TITLE
Carousel not showing up on frontpage

### ISSUE THREAD

**Issue by annawada** [Japan-Digital-Archives/Japan-Digital-Archive#849]
Tried with Chrome and Firefox browsers.

**Comment by corinnecurcie** [comment]
Hi Anna, this is actually for right now a controlled take-down of the
carousel. The carousel was causing loading times of 25-35seconds for the
homepage, resulting from a large import made recently to our database. I'm
attempting to rewrite the query that populated the carousel in order to not
have this slowdown, so for now I've taken it down, as it doesn't
significantly alter user experience but the loading times were extremely
impactful.

On Wed, Oct 15, 2014 at 10:25 PM, annawada notifications@github.com wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/849
> .

## 

Corinne Curcie
Harvard University
Class of 2015
Computer Science
