### ISSUE TITLE
Michinoku Shinrokuden, MediaCreatorUsername IRIDes, Images disappeared.

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#855]
This issue may be the same problem as #801.  After the Yahoo image problem was fixed, some Michinoku Shinrokuden images (ID 891338 ~ 913881) are not appearing in the JDA site.
![media creator username irides images](https://cloud.githubusercontent.com/assets/8831502/4692060/b0b18f88-5748-11e4-89a3-030c7b1474d9.png)

**Comment by corinnecurcie** [comment]
This might be on Michinoku Shinrokuden's end. It looks like the data is still the same, we have URIs like http://michinoku.irides.tohoku.ac.jp/michinoku-archive/photo/4/10615620461502.jpg which must be scraped from their end, but they don't work. It's not like our data is lost, it's that the links are broken.

**Comment by corinnecurcie** [comment]
Michinoku Shinrokuden used to have an old URL system where all the URLs started with "michinoku.irides....". When this was the case, we imported those images with IDs 891338 ~ 913881 (about 22,000). After that, they switched to URLs that all started with "search.shinrokuden...". Unfortunately, the URLs did not correlate at ALL in terms of ID in the url, so we could not control for duplicates getting added, because we could not figure out when an old URL and a new URL meant the same image, since there is no way of correlating. So, we imported ALL the new URLs (which possibly inlcuded ~22,000 duplicates), but we had no way of checking in the URLs. And we never noticed these duplicates when using the archive, so potentially the 22,000 previous items could be completely different than the new ones, but again, with the different URLs, we couldn't check.

The old URLs "michinoku.irides..." still worked, and were in users' collections, which is why we never deleted them and just used all the new URLs. However, it looks like, finally, they have stopped supporting the old URLs, so now we have about 22,000 items that won't show up. 

You can see the difference in URLs in the dashboard. All the items for user 429 below ID 913881: 
http://jdarchive.org/admin/zeega/data/item/list?filter%5B_sort_order%5D=ASC&filter%5B_sort_by%5D=id&filter%5B_page%5D=1&filter%5Btitle%5D%5Btype%5D=&filter%5Btitle%5D%5Bvalue%5D=&filter%5Buri%5D%5Btype%5D=&filter%5Buri%5D%5Bvalue%5D=&filter%5Bpublished%5D%5Btype%5D=&filter%5Bpublished%5D%5Bvalue%5D=&filter%5Bmedia_type%5D%5Btype%5D=&filter%5Bmedia_type%5D%5Bvalue%5D=&filter%5Blayer_type%5D%5Btype%5D=&filter%5Blayer_type%5D%5Bvalue%5D=&filter%5Bmedia_creator_username%5D%5Btype%5D=&filter%5Bmedia_creator_username%5D%5Bvalue%5D=&filter%5Bmedia_creator_realname%5D%5Btype%5D=&filter%5Bmedia_creator_realname%5D%5Bvalue%5D=&filter%5Bid%5D%5Btype%5D=4&filter%5Bid%5D%5Bvalue%5D=913881&filter%5Buser_id%5D%5Btype%5D=3&filter%5Buser_id%5D%5Bvalue%5D=429

If you click on any of those, you will see the URIs all start with "michinoku.irides..."

All the items for user 429 ABOVE the ID 913881: http://jdarchive.org/admin/zeega/data/item/list?filter%5Btitle%5D%5Btype%5D=&filter%5Btitle%5D%5Bvalue%5D=&filter%5Buri%5D%5Btype%5D=&filter%5Buri%5D%5Bvalue%5D=&filter%5Bpublished%5D%5Btype%5D=&filter%5Bpublished%5D%5Bvalue%5D=&filter%5Bmedia_type%5D%5Btype%5D=&filter%5Bmedia_type%5D%5Bvalue%5D=&filter%5Blayer_type%5D%5Btype%5D=&filter%5Blayer_type%5D%5Bvalue%5D=&filter%5Bmedia_creator_username%5D%5Btype%5D=&filter%5Bmedia_creator_username%5D%5Bvalue%5D=&filter%5Bmedia_creator_realname%5D%5Btype%5D=&filter%5Bmedia_creator_realname%5D%5Bvalue%5D=&filter%5Bid%5D%5Btype%5D=2&filter%5Bid%5D%5Bvalue%5D=913881&filter%5Buser_id%5D%5Btype%5D=3&filter%5Buser_id%5D%5Bvalue%5D=429&filter%5B_page%5D=1&filter%5B_sort_by%5D=id&filter%5B_sort_order%5D=ASC

These all have the new URL, "search.shinrokuden..."

So the issue is with Michinoku Shinrokuden no longer supporting the URLs that start with "michinoku.irides" even though we still have them in our database. 

Unfortunately, I can't exactly do "ret-con" to just update the URIs to the right format, because like I said above, the image IDs in the MS database don't match up, and they're in two different formats that don't seem to be convertible to each other. If we contact Michinoku Shinrokuden and they tell us how to convert the old URIs to the new format (if there is such a way - again, there might not be), then I can salvage the 22,000~ images. Otherwise, they will have to be deleted.

**Comment by jdaKoko** [comment]
Thank you!
