### ISSUE TITLE
Seed submission problems

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#889]
1/3/15
There are two problems regarding seed submissions: conventional seed submission through the contribute page and submission through bookmarklet.
The submissions do not appear on the admin dash page.
The bookmarklet submission results say, "There was a problem adding this item!"
![bookmarklet](https://cloud.githubusercontent.com/assets/8831502/5603944/4d92bf3a-936b-11e4-8915-176bbbe08f7d.png)

**Comment by jdaKoko** [comment]
1/4/15
Submitted seeds are now appearing on the admin dashboard.  However, seeds which published on  1/4/15 are not appearing in on the JDA search.

**Comment by corinnecurcie** [comment]
Hi Koko,

The error message result may have been a very temporary and poorly-scheduled fault on my part from when I was re-importing the Yahoo data. In order to get the Yahoo data to go back into the 1-20,000 ID slots in the database, I had to turn off the automatic "ID-assigning" that normally happens when you submit an item, where it just adds it onto the end of the database. So for a brief period of time, that system wasn't in place, meaning any item that was submitted without an explicit "ID" field would have been rejected, which probably resulted in that error. I changed the files back after the Yahoo import was done, but there were a few hours where submissions wouldn't have worked. I'm so sorry about that - I should have warned you but it completely slipped my mind. Can you test and let me know if bookmarklet submission is working for you now? 

As for the seeds, I believe that should be fixed along with the other seed-related issues that were just sorted with the re-index. However, items that you tried to submit that resulted in the error message will have to be resubmitted, unfortunately. Again, I'm really sorry! 

Anyway, please close this if you think the issue is resolved, otherwise please let me know what else is still causing trouble =)

**Comment by jdaKoko** [comment]
Dear Corinne, 
Bookmarklet and the submission page are working now. Thank you very much for fixing.
