### ISSUE TITLE
Published seeds after 1/4/15 and 311 memory items are not appearing on the JDA search

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#891]
There is a similar problem to #863.
Published seeds on 1/4/15 are not appearing in the JDA search.
311 memory items after ID1554303 are not appearing in the JDA search.

**Comment by corinnecurcie** [comment]
Since I just added in all the Yahoo data back (hooray), this might be a Solr issue, so I'm re-indexing.

**Comment by corinnecurcie** [comment]
Okay, I think the re-index worked. I'm seeing a ton of 311 Memory items with IDs after 1554303, as well as a few 1/4/15 RIJS posts. Does this also resolve #863? I am seeing 311 items with IDs higher than 1931433, so hopefully this has been worked out. 

I'm really sorry for the hassle... I'm going to see if I can automize the SOLR re-indexing so that it occurs once a day or something, so that we don't get stuck like this.

**Comment by jdaKoko** [comment]
Yes! Thank you very much. Now I can see my latest submissions and 311 memory items.
I think this resolved #863.  I'd appreciated it very much if you could automize the SOLR re-indexing.
