### ISSUE TITLE
Talk with Jessica about "import to waku" link

### ISSUE THREAD

**Issue by corinnecurcie** [Japan-Digital-Archives/Japan-Digital-Archive#955]
Pass through collection number to Waku (even after google authentication)

**Comment by corinnecurcie** [comment]
Email sent

**Comment by meeshmon** [comment]
Integration of Waku into JDA so that the user can access Waku directory from the collection page.

**Comment by horak** [comment]
> Passing through collection number to Waku

Could this be accomplished with a little bookmarklet that would be pressed on a collection page and open up the waku site?

> access Waku directory from the collection page.

What type of access are you thinking here? 

Another idea might be to throw wacu into an iframe on JDA but that'll most likely not be very pretty. @jessyurko, are there any specific reasons you built wacu separately?

**Comment by jessyurko** [comment]
> Could this be accomplished with a little bookmarklet that would be pressed on a collection page and open up the waku site?

Yes definitely. One issue I can think of might be confusion between this and the "add to jda" bookmarklet, but worth thinking about pros/cons compared to a direct link from a collection page.

> What type of access are you thinking here?

I suspect the ability to create new waku projects from that collection, see existing public wakus made by other users from that collection, see any of your own wakus created from that collection.

> are there any specific reasons you built wacu separately?

To have more control over development environment; to have a bit more freedom in thinking about interoperability with other platforms (namely Curarium); efficiency (versus integrating with existing zeega backend); because I feel more comfortable with javascript :)

**Comment by horak** [comment]
Ok I added a little (admittedly ugly but hopefully style conforming) dialogue window to help tell new users a little bit about waku. Jessica, what do you think that text should read?
![screenshot](https://cloud.githubusercontent.com/assets/1111424/8367591/d73aa538-1b6d-11e5-8d08-82404fbd19ef.png)

**Comment by jessyurko** [comment]
I like this text! Maybe capitalize "Create Waku"? Also, let's think about icons -- I'll look through font awesome / noun project and see if I can find anything.

**Comment by horak** [comment]
@meeshmon, Jess said this little text blurb should be fine to use, here is what google translate tells me, can you audit?

Wakuにこのコレクションを使用して、メディアリッチな物語を構築します。Wakuがキュレーションとプレゼンテーションのためのストーリーテリングプラットフォームです、それは試してみます！

**Comment by meeshmon** [comment]
Waku使うことによって、このコレクションをマルチメディアな物語へと構築することができます。Wakuはキュレートされた震災記録から個人の物語を紡ぎ、発表、シェアできるプラットフォームです。ぜひお試しください!

**Comment by horak** [comment]
Ok great this is all ready to go. Jessica, let me know when you find an icon you like!

**Comment by meeshmon** [comment]
Any update on this issue?

**Comment by horak** [comment]
Cool, I merged this and it's live. We can replace the icon and style later on.
