### ISSUE TITLE
Import Asahi JW May 2015 data 

### ISSUE THREAD

**Issue by meeshmon** [Japan-Digital-Archives/Japan-Digital-Archive#980]
Their April data is ready to be imported.

**Comment by meeshmon** [comment]
Their May data is ready to be imported.

**Comment by horak** [comment]
Cool, i'll do that next week.

**Comment by horak** [comment]
What's the path where they drop this data into?

**Comment by meeshmon** [comment]
https://github.com/Japan-Digital-Archives/scripts/wiki/Asahi-Asia-&-Japan-Watch-Import-Notes

**Comment by horak** [comment]
That link doesn't work but I found it! I'll added a wiki page for future reference to it's location and the Asahi import process.

**Comment by meeshmon** [comment]
@horak Can you try the link again? I just added you to the list of owners.

**Comment by horak** [comment]
Sweet :+1:

**Comment by horak** [comment]
Ok running into a bit of problem, maybe you can help me out here @meeshmon:

I've imported the data properly according to the S3 & Sonata. Unfortunately I'm not seeing that data reflected properly on [my dev instance](http://dev.jdarchive.org/alex/web/en/user/468). What would you recommend I do here? It is interesting to note that corinne's [dev instance](http://dev.jdarchive.org/corinne/web/en/user/468) doesn't indicate anything here either.

**Comment by meeshmon** [comment]
hmm maybe there is a step corinne did not put in the wiki. 
@horak Do you have a note from the time when corinne went over this with you that
might indicate what needs to be done? If not the next step would be to contact corinne.

**Comment by corinnecurcie** [comment]
Hi Alex,

You have to index solr afterwards, as is described here:
https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/wiki/Adding-data-to-the-archive#importing-to-production

Sorry I forgot to include it on the Asahi instructions - it's the standard
workflow for all content imports so I forgot! Once you reindex solr (and
make sure youre on the production solr through localhost, not dev, just
make sure you follow the section I linked and not the one before it) you
should see it.

On Tue, Jun 16, 2015 at 6:43 PM, meeshmon notifications@github.com wrote:

> hmm maybe there is a step corinne did not put in the wiki.
> @horak https://github.com/horak Do you have a note from the time when
> corinne went over this with you that
> might indicate what needs to be done? If not the next step would be to
> contact corinne.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/980#issuecomment-112620854
> .

## 

Corinne Curcie
Harvard University
Class of 2015
Computer Science

**Comment by corinnecurcie** [comment]
Oh, I see you're talking about your dev instance. In that case, you DO want
to reindex on dev, described in the previous section to the one I linked,
"general data import workflow".

Also as I mentioned in our meeting, I've found that importing on the dev
server often imports to the production database as well. So you should
check whether the content has appeared on the production server, because if
so, you don't want to import to the production server again and cause
duplicates. You can use the admin dashboard to check if the content has
spread to the production side, or just use the --check_for_duplicates flag
on import to the production server which will skip duplications.

On Tue, Jun 16, 2015 at 6:58 PM, Corinne Curcie corinnecurcie@gmail.com
wrote:

> Hi Alex,
> 
> You have to index solr afterwards, as is described here:
> https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/wiki/Adding-data-to-the-archive#importing-to-production
> 
> Sorry I forgot to include it on the Asahi instructions - it's the standard
> workflow for all content imports so I forgot! Once you reindex solr (and
> make sure youre on the production solr through localhost, not dev, just
> make sure you follow the section I linked and not the one before it) you
> should see it.
> 
> On Tue, Jun 16, 2015 at 6:43 PM, meeshmon notifications@github.com
> wrote:
> 
> > hmm maybe there is a step corinne did not put in the wiki.
> > @horak https://github.com/horak Do you have a note from the time when
> > corinne went over this with you that
> > might indicate what needs to be done? If not the next step would be to
> > contact corinne.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/980#issuecomment-112620854
> > .
> 
> ## 
> 
> Corinne Curcie
> Harvard University
> Class of 2015
> Computer Science

## 

Corinne Curcie
Harvard University
Class of 2015
Computer Science

**Comment by horak** [comment]
Yeah the dev db ingestion went well, that's what's so strange:
`Ingestion complete. 34 items added to the database. 0 items updated. 0 duplicates found.`

The solr index on DEV was also successful:
![solr-dev](https://cloud.githubusercontent.com/assets/1111424/8209845/389fc962-14dd-11e5-971e-ace837e6f11f.png)

And as you mentioned it might, my data import into dev actually shows up in the Sonata Admin. Which is why I'm confused as to why it's not showing up on my dev instance.

I'm also confused as to where I'm supposed to check the dev sonata database? Is there a url there I missed?

**Comment by horak** [comment]
@corinnecurcie So I'm thinking that what happened is that the data was _only_ uploaded to the production db and _not_ the development db. But again, not sure exactly where the dev db is located. There are two instances on RDS, `jda` & `zeega` but neither seem like a dev one (and I don't have the credentials to check the `zeega` instance. Let me know what you think!

**Comment by meeshmon** [comment]
@corinnecurcie I know you are busy but can you advice Alex on this ASAP? In a week or so, AJW will upload another batch of their headlines.

**Comment by horak** [comment]
@corinnecurcie so I went through [general import flow](https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/wiki/Adding-data-to-the-archive#general-data-import-workflow) again today just in case I missed something but unfortunately turned up with similar results: I have no way of confirming the imported data shows up properly on my dev server. User 468 [doesn't show any collection data whatsoever unfortunately](http://dev.jdarchive.org/alex/web/en/user/468#q=asahi shimbun&media_type=&sort=relevant&). This leads me to believe there is a systemic issue with the development database because it should at least show data from previous imports. As of right now I have no way of confirming the data was imported properly and so feel hesitant to upload anything to production.

**Comment by corinnecurcie** [comment]
That does sound like a problem with the dev database, which wouldn't surprise me since that thing has always been a mystery to me. If you copy just 2 or 3 of the json entries into a file with the proper "items" array and syntax, and upload that to production, you can test that import without breaking anything. When you see the new data both in the admin dashboard and on user 468's page without any text formatting problems or image issues, you should be set to upload the full import.

**Comment by horak** [comment]
I see ok that's a bummer but will do, thanks!
